### ISSUE TITLE
Requested additional features

### ISSUE THREAD

**Issue by ZsZolee** [jimmyff/crypto-clock#1]
Hi! First of all, I love your work! Please if it's possible, add these details too: Block high, SAT/USD, Transactions (24h), Hashrate (EH/s), Total BTC issued, Trade volume (/h). I would love to see these too.

**Comment by jimmyff** [comment]
Hey thanks for the kind words. This project was a bit of a one off as it was a gift for someone. I'm afraid I don't have any plans to add additional features at this time. I would however welcome pull requests if yourself or anyone else wanted to improve it.

I'm going to close this issue for now as those features are out of scope of the current project. Thanks
